In [ ]:
import numpy as np
from scipy import linalg

# ตัวอย่างที่ 16

A = np.array([[1, 5, 0], [0, -3, 1], [2, 4, -1]]) 

print(A, '\n') 

print(linalg.det(A), '\n')

[[ 1  5  0]
 [ 0 -3  1]
 [ 2  4 -1]] 

9.0 



In [ ]:
# ตัวอย่างที่ 19

B = np.array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]]) 

print(B, '\n') 

print(linalg.det(B), '\n')

[[ 1  1  0  3]
 [ 2  1 -1  1]
 [ 3 -1 -1  2]
 [-1  2  3 -1]] 

39.0 



In [ ]:
# ตัวอย่าง 24

C = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]]) 

print(C, '\n') 

print(linalg.det(C), '\n')

print(linalg.inv(C), '\n')

d = np.array([5, 3, 17]) 

print(np.linalg.solve(C,d), '\n')

[[1 2 3]
 [2 5 3]
 [1 0 8]] 

-1.0000000000000004 

[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]] 

[ 1. -1.  2.] 



In [ ]:
#Row Reduce

A = np.array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]]) 
n = len(A)
for k in range(n-1) :
  for i in range(k+1,n) :
    u = A[i,k]/A[k,k]
    for j in range(k,n) :
      A[i,j] = A[i,j] - u*A[k,j]
print(A)

[[  1   1   0   3]
 [  0  -1  -1  -5]
 [  0   0   3  13]
 [  0   0   0 -13]]


In [ ]:
#Inverse
from scipy import linalg
np.set_printoptions(precision=6)

A = np.array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]]) 
B = A
if abs(linalg.det(A)) > 0.00000000000000000001 :
  n = len(A)
  A = np.column_stack((A, np.identity(n)))
  print(A)

  x = np.zeros(4)
  for k in range(n) :
    for i in range(k+1,n) :
      u = A[i,k]/A[k,k]
      for j in range(k,n+n) :
        A[i,j] = A[i,j] - u*A[k,j]
    for i in range(k-1,-1,-1) :
      u = A[i,k]/A[k,k]
      for j in range(k,n+n) :
        A[i,j] = A[i,j] - u*A[k,j]
    print(A)

  for i in range(n) :
    A[i][:] = A[i][:]/A[i][i]
  print(A)

  C = np.split(A, 2, axis=1)
  Ainverse = C[:][1]
  print(Ainverse)
  print(linalg.inv(B), '\n')

[[ 1.  1.  0.  3.  1.  0.  0.  0.]
 [ 2.  1. -1.  1.  0.  1.  0.  0.]
 [ 3. -1. -1.  2.  0.  0.  1.  0.]
 [-1.  2.  3. -1.  0.  0.  0.  1.]]
[[ 1.  1.  0.  3.  1.  0.  0.  0.]
 [ 0. -1. -1. -5. -2.  1.  0.  0.]
 [ 0. -4. -1. -7. -3.  0.  1.  0.]
 [ 0.  3.  3.  2.  1.  0.  0.  1.]]
[[  1.   0.  -1.  -2.  -1.   1.   0.   0.]
 [  0.  -1.  -1.  -5.  -2.   1.   0.   0.]
 [  0.   0.   3.  13.   5.  -4.   1.   0.]
 [  0.   0.   0. -13.  -5.   3.   0.   1.]]
[[  1.         0.         0.         2.333333   0.666667  -0.333333
    0.333333   0.      ]
 [  0.        -1.         0.        -0.666667  -0.333333  -0.333333
    0.333333   0.      ]
 [  0.         0.         3.        13.         5.        -4.
    1.         0.      ]
 [  0.         0.         0.       -13.        -5.         3.
    0.         1.      ]]
[[  1.         0.         0.         0.        -0.230769   0.205128
    0.333333   0.179487]
 [  0.        -1.         0.         0.        -0.076923  -0.487179
    0.333333  -0.051282

In [ ]:
#Gauss Elimination

A = np.array([[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]]) 
if linalg.det(A) > 0.00000000000000000001 :
  b = np.array([4, 1, -3, 4])
  A = np.column_stack((A, b))
  print(A)
  n = len(A)
  x = np.zeros(4)
  for k in range(n-1) :
    for i in range(k+1,n) :
      u = A[i,k]/A[k,k]
      for j in range(k,n+1) :
        A[i,j] = A[i,j] - u*A[k,j]
  x[n-1] = A[n-1,n]/A[n-1,n-1]
  for i in range(n-2,-1,-1) :
    sum = 0
    for j in range(i+1,n) :
      sum = sum + A[i,j]*x[j]
    x[i] = (A[i,n] - sum)/A[i,i]
  print(A)
  print(x)

[[ 1  1  0  3  4]
 [ 2  1 -1  1  1]
 [ 3 -1 -1  2 -3]
 [-1  2  3 -1  4]]
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]
[-1.  2.  0.  1.]
